version: 2 # use CircleCI 2.0
jobs: # collection of steps
  build:
    docker:
      - image: circleci/node:10.15.3-jessi
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
